### ISSUE TITLE
Contribution policy?

### ISSUE THREAD

**Issue by StefanSchubert** [bcleonard/boinc#1]
Hi thanks for the container. I would like to propose some additions to the documentations.
How to contribute - I can't push branches or make pull requests.

Greetings from Germany
Stefan

**Comment by bcleonard** [comment]
Stefan,

The recommended way is as follows:

* Fork the project & clone locally.
* Create an upstream remote and sync your local copy before you branch.
* Branch for each separate piece of work.
* Do the work, write good commit messages, and read the CONTRIBUTING file if there is one.
* Push to your origin repository.
* Create a new PR in GitHub.
* Respond to any code review feedback.

These came from [The beginner's guide to contributing to a GitHub project.](https://akrabat.com/the-beginners-guide-to-contributing-to-a-github-project/#summary)

I've use this a few times in contributing to some projects.  Let me know if you need any assistance.

**Comment by StefanSchubert** [comment]
Thanks for the explanations, I always thought forking would be used if one intents to copy (safe the existing work) and develop into another direction (example MySQL->MariaDB). And that cloning would be the right way, if some one does not intent to keep the repo and develop into another direction (Same as collaboration in commercial projects).

Anyway if forking is the standard procedure for this, it's fine with me. I guess it's standard to destroy the fork afterwards, if the change has been accepted, right?

Happy weekend.
Stefan
