### ISSUE TITLE
Dockerhub Client seem stale since 3.4.

### ISSUE THREAD

**Issue by StefanSchubert** [bcleonard/boinc#4]
Hi there,

thanks for the container!
It looks like that there exists a new client since 3.Apr.2020. The current container on dockerhub doesn't seem to accept new workpackages (at least for the covid-19 figth on Rosetta)

Cheers,
Stefan

**Comment by bcleonard** [comment]
I'm no longer going to be maintaining this project.   After receiving your issue, I'm been doing some planned upgrades & maintenance.  As a result, I've switched to the official BOINC docker client.  

This didn't exist when I first created this project.  After playing with it for the past couple of days, I've moved all my boinc processing to it.

https://hub.docker.com/r/boinc/client
